name: Docker Image CI cron

on:
  push:
  schedule:
    - cron: '0 0 3 * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to github Registry
      uses: docker/login-action@v1
      with:
        registry: "https://index.docker.io/v1/"      
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image to container Registry
      run: |
        docker build . --file Dockerfile
