name: Build Docker Image no push

on:
  pull_request:
  push:
      
env:
  TAG: "python-vol2birds"
  DOCKERHUB_IMAGE_ID: "qcdis/"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to github Registry
      uses: docker/login-action@v2
      with:
        registry: "https://index.docker.io/v1/"      
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push to container Registry
      run: |
        docker build . --file Dockerfile -t $TAG
