name: Docker Image CI

on:
  push:
    tags:
      - '*'
      
env:
  TAG: "python-vol2birds"
  DOCKERHUB_IMAGE_ID: "qcdis/"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to github Registry
      uses: docker/login-action@v1
      with:
        registry: "https://index.docker.io/v1/"      
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push to container Registry
      run: |
        docker build . --file Dockerfile -t $TAG
        # Change all uppercase to lowercase
        IMAGE_ID=$DOCKERHUB_IMAGE_ID$TAG
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $TAG $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        docker tag $TAG $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
